### ISSUE TITLE
Realm.close() causing crash running on different thread

### ISSUE THREAD

**Issue by dkpalmer** [kboyarshinov/realm-rxjava-example#1]
In the latest release of Realm (v0.82.1), the call to close the Realm crashes due to:

Caused by: java.lang.IllegalStateException: Realm access from incorrect thread. Realm instance can only be closed on the thread it was created.

I originally tried your example and couldn't get it to crash, but when I bumped Realm to v0.82.1 I saw the same behavior.

**Comment by dkpalmer** [comment]
I got around the issue by moving the close() call to the end of the OnSubscribeRealmResults call method.  I haven't looked deep enough to identify if this has any side effects though?

**Comment by kboyarshinov** [comment]
It appears the same issue https://github.com/realm/realm-java/issues/1402. Check if you have correct schedulers in `subscribeOn/observeOn` operators.

**Comment by dkpalmer** [comment]
Yes, if I use the same thread for both operators it adheres to Realm's same thread requirement.  However, in my case I want to fetch data in the background and then display the data on the main thread, similar to your example app.

**Comment by kboyarshinov** [comment]
You cannot use realm object directly in any thread but one it was created. That's why in this example original realm objects are mapped to simple POJO objects. Do you do the same?

**Comment by dkpalmer** [comment]
Yes, I do the same.  As I mentioned above, I also reproduced the same behavior in your sample app just by bumping Realm to v0.82.1.

**Comment by kboyarshinov** [comment]
Ok. I'll investigate this. Thanks

**Comment by dkadrikj** [comment]
I also have the same problem. Will investigate too and if I find something I will post the findings

**Comment by dkadrikj** [comment]
One more thing, everything works great with Realm 0.81.1

**Comment by dkpalmer** [comment]
Yeah, it would've started in 0.82.  Per Realm changelog:

0.82
- Closing realm on another thread different from where it was created now throws an exception.

**Comment by kboyarshinov** [comment]
Sorry guys. Haven't got time yet to dig into this. 

According to this changelog it can break unsubscribe logic if something goes wrong. Unsubscribe action should happen in the same scheduler passed in `subscribeOn` as I understand. Probably, `unsubscribeOn` operator can help. Need to check this

**Comment by dkadrikj** [comment]
Yes, I did some research, and I saw that realm.close() is invoked on the main thread. 

subscriber.add(Subscriptions.create(() -> {
            try {
                realm.close();
            } catch (RealmException ex) {
                subscriber.onError(ex);
            }
        }));

The workaround is to put only the realm.close() at the end of the method (this way it gets invoked on the background thread). I haven't checked with unsubscribeOn, but I will.

**Comment by kboyarshinov** [comment]
Yes. Investigated this yesterday too. Unsubscribe is always called on the same thread `observeOn` is defined. 

Putting `realm.close()` at the end of method is not acceptable solution because this way manual unsubscribe would not be called and realm instance won't be closed causing a leak. I already have some solution close to required behaviour but it still has some problems. I'll continue working on it in few hours.

`unsubscribeOn` can not help too because it accepts Schedulers. Thus subscribe and unsubscribe action could happen on different threads from one thread pool.

**Comment by dkadrikj** [comment]
What do you mean by manual unsubscribe will not be called? The realm is always closed after each interaction, so it won't leak.

**Comment by kboyarshinov** [comment]
I mean there can be a situation with realm doing a lot of work in background thread and activity or fragment will be closed with `unsubscribe` call. With `realm.close()` at the end of `subscribe` method and without special `unsubscribe` action doing this realm instance closing `unsubscribe` call will cause this thread to be interrupted. Thus realm instance will be leaked.

Sure, it is unlikely for realm to do a lot of work cause it's fast, but it can happen in theory.

**Comment by dkadrikj** [comment]
Yes, sure, I understand. I didn't take into account that the operation can get slow. Also, about the unsubscribeOn it will difficult to track the same thread on which the the subscription was opened.

**Comment by kboyarshinov** [comment]
> it will difficult to track the same thread on which the the subscription was opened

That's what I'm trying to do now :)

**Comment by kboyarshinov** [comment]
@dkadrikj @dkpalmer I have updated the example with solved issue. I use manual thread interruption to handle unsubscribe case and close Realm instance in the same thread it was created. Realm IO process itself is native and non-interruptable so when unsubscribed it will wait to finish and transaction will be canceled in this case. Check [OnSubscribeRealm](https://github.com/kboyarshinov/realm-rxjava-example/blob/master/app/src/main/java/com/kboyarshinov/realmrxjavaexample/rx/OnSubscribeRealm.java) class for details. Other onSubscribe functions became obsolete and I deleted them. RealmObservable API stays the same.

Also I updated libraries. Now example uses new RealmConfiguration API to create Realm instances.

Check the updated version and if everything is ok I'll close the issue.

**Comment by kboyarshinov** [comment]
@dkadrikj @dkpalmer please share your feedback for updated version.

**Comment by dkpalmer** [comment]
Overall it looks straightforward to me.  The only thing that caught my eye was the "while (!interrupted)" loop.  Is the getter likely to return null, where retrying will eventually succeed?  Or if it does return null, is there a case that can go uninterrupted but always return null?  I can comment inline and we can discuss there if you'd prefer.

**Comment by kboyarshinov** [comment]
@dkpalmer This loop is pretty common in IO operations to handle thread interruption. But since Realm IO is non-interruptable I guess it can be deleted and thread can be checked for interruption afterwards. In this case there will no be attempt to retry operation. AFAIK Realm will not return null, but better to have this check anyway :). I'll update an retest in few hours.

Overall does it works for you? Did you have any issues with chaining rx operations (e.g. request find object by object -> get project id -> find list of other objects by this id)?

EDIT: removed while loop, tested, seems fine.

**Comment by dkpalmer** [comment]
Finally had a chance to port in the changes and test.  Unfortunately I ran into issues:

I loop over a list of models and call a method to insert/update each model.  That method that makes a call to 'copyToRealmOrUpdate' and then maps to convert my model from Realm flavor to non-Realm flavor.  The first pass works, but on subsequent passes the thread is interrupted and transactions are thus canceled.  I'm guessing this is from the OnSubscribeRealm's call method, and a result of my for loop  on a single thread.  Thoughts on how to best handle this?

**Comment by kboyarshinov** [comment]
Not getting why this happening. Can you post sample code please?

**Comment by dkpalmer** [comment]
I'll try to put together a similar sample w/ your example project.  Looking at differences between your example and my project, I do have a blocking observable (Observable.toBlocking( )) call.  I have a feeling this might be the culprit and something I can get around by properly chaining.

**Comment by dkadrikj** [comment]
@kboyarshinov Pretty clear solution, everything seems good to me. Works perfect. I am using also version 0.83 snapshot.

**Comment by kboyarshinov** [comment]
@dkpalmer Thank you. Probably `toBlocking` causing a problem, because thread reference is stored without check on main thread, and it may be interrupted in case of early unsubcribe. Worth checking.

@dkadrikj Appreciate your feedback.

**Comment by kboyarshinov** [comment]
After testing I noticed that new implementation does not work well with `zip` operator and probably with all combine operators. @dkpalmer @dkadrikj Please take that into account.

**Comment by dkadrikj** [comment]
@kboyarshinov what is the problem? I havent noticed anything yet.

**Comment by kboyarshinov** [comment]
@dkadrikj Zipping two or more Realm observables is performed in single sequence on one thread. When first observable finishes zip operator unsubscribes it causing a thread to interrupt. And when next observables start executing thread is already interrupted and observable cancels Realm transaction.

**Comment by kboyarshinov** [comment]
I slightly updated `RealmObservable`. Replaced thread interruption with `AtomicBoolean` based cancellation. Added check for single subscriber on single `OnSubscribeRealm` instance to have one `AtomicBoolean` per subscriber. It means something like that will cause a crash:

``` java
Observable<Issue> issues = dataService.issues();
Observable.zip(issues.takeFirst(10), issues.takeLast(10)), ...).subscribe(...)
```

And this won't:

``` java
Observable.zip(dataService.issues().takeFirst(10), dataService.issues().takeLast(10)), ...).subscribe(...)
```

Also added few examples with `zip` and `flatMap`.

@dkpalmer This change will probably solve your issue with blocking observable.

**Comment by kboyarshinov** [comment]
Oops. Find out that I forgot to push changes on weekend. Pushed them.

Now I'm working on multiple subscribers support and few other tests to determine possible problems.

**Comment by kboyarshinov** [comment]
Added support for multiple subscribers. Working fine for now. No issues with different use cases and scenarios.

@dkpalmer @dkadrikj Please check.

**Comment by dkadrikj** [comment]
@kboyarshinov  Finally found some time to do some tests. I am getting this error:

"This Realm instance has already been closed, making it unusable."

**Comment by dkadrikj** [comment]
Yes, the issue was calling .toList() and after that map().  It is kind of limitation.

**Comment by kboyarshinov** [comment]
@dkadrikj Can you provide code example please? I checked this like `dataService.issues().take(5).toList().map(issues -> issues.get(0))` - no issue.

**Comment by dkadrikj** [comment]
@kboyarshinov  For example, if I have a method in a class called RealmStore which returns:

public Observable<List<LocationEntity>> getLocations() {
    return RealmObservable.results(context, realm
                -> realm.where(LocationEntity.class).findAll()).flatMap(Observable::from).toList();
}

and, if the calling method does this:
    realmStore.getLocations().map(...);

then the error occurs.
So, in order to fix this, all the transformation operations has to be done in the lowest level where the observable is actually created. If you have some data module which provides the data, and you want to do some transformation in the same thread but in some of the calling methods, then this is a limitation.

**Comment by kboyarshinov** [comment]
@dkadrikj Thanks for the example. Checked it now. It happens because `toList()` operator waits for observable to finish emitting and `onCompleted()` event to occur in order to emit the resulted list. But also `onCompleted` causes Realm instance to close and all of RealmObjects become invalid. I'll think on how to fix it.

**Comment by dkadrikj** [comment]
@kboyarshinov anything new about this? Or just not using toList() in the middle of transformations?

**Comment by kboyarshinov** [comment]
@dkadrikj haven't got into this yet. Probably yes, best for now is really not to use `toList()` in the middle of transformation. Try to keep realm requests simple in order to operate on your POJO objects, it will decrease possibility of bugs. Hope we have native RxJava support in Realm soon.

**Comment by kboyarshinov** [comment]
Realm finally [gets](https://realm.io/news/realm-java-0.87.0/) native RxJava support! I'm closing this.
